-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 15:53:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Fabrica_de_sorvete
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Fabrica_de_sorvete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Fabrica_de_sorvete` DEFAULT CHARACTER SET utf8 ;
USE `Fabrica_de_sorvete` ;

-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`tipos_embalagems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`tipos_embalagems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`tipo_embalagem_picole_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`tipo_embalagem_picole_normal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_embalagem` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_embalagem_2_idx` (`id_embalagem` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_embalagem_2`
    FOREIGN KEY (`id_embalagem`)
    REFERENCES `Fabrica_de_sorvete`.`tipos_embalagems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`aditivos_nutritivos_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`aditivos_nutritivos_normal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `formula_quimica` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`aditivo_nutritivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`aditivo_nutritivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aditivo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aditivo_normal_1_idx` (`id_aditivo` ASC) VISIBLE,
  CONSTRAINT `fk_aditivo_normal_1`
    FOREIGN KEY (`id_aditivo`)
    REFERENCES `Fabrica_de_sorvete`.`aditivos_nutritivos_normal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`sabores_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`sabores_normal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`ingredientes_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`ingredientes_normal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`ingredientes_picoles_NORMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`ingredientes_picoles_NORMAL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ingredientes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredientes_1_idx` (`id_ingredientes` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_1`
    FOREIGN KEY (`id_ingredientes`)
    REFERENCES `Fabrica_de_sorvete`.`ingredientes_normal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`picole_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`picole_normal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preço` DECIMAL(8,2) NOT NULL,
  `id_sabor` INT NOT NULL,
  `id_ingredientes` INT NOT NULL,
  `id_embalagem` INT NOT NULL,
  `id_aditivos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picole_1_idx` (`id_embalagem` ASC) VISIBLE,
  INDEX `fk_picole_2_idx` (`id_aditivos` ASC) VISIBLE,
  INDEX `fk_picole_3_idx` (`id_sabor` ASC) VISIBLE,
  INDEX `fk_picole_4_idx` (`id_ingredientes` ASC) VISIBLE,
  CONSTRAINT `fk_picole_1`
    FOREIGN KEY (`id_embalagem`)
    REFERENCES `Fabrica_de_sorvete`.`tipo_embalagem_picole_normal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picole_2`
    FOREIGN KEY (`id_aditivos`)
    REFERENCES `Fabrica_de_sorvete`.`aditivo_nutritivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picole_3`
    FOREIGN KEY (`id_sabor`)
    REFERENCES `Fabrica_de_sorvete`.`sabores_normal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picole_4`
    FOREIGN KEY (`id_ingredientes`)
    REFERENCES `Fabrica_de_sorvete`.`ingredientes_picoles_NORMAL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`sabores_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`sabores_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`picole_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`picole_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preço` DECIMAL(8,2) NOT NULL,
  `id_sabor` INT NOT NULL,
  `id_embalagems` INT NOT NULL,
  `id_ingredientes` INT NOT NULL,
  `id_conservantes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sabor_1_idx` (`id` ASC, `id_sabor` ASC) VISIBLE,
  INDEX `embalagem_idx` (`id_embalagems` ASC) VISIBLE,
  CONSTRAINT `sabor_1`
    FOREIGN KEY (`id` , `id_sabor`)
    REFERENCES `Fabrica_de_sorvete`.`sabores_ao_leite` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `embalagem`
    FOREIGN KEY (`id_embalagems`)
    REFERENCES `Fabrica_de_sorvete`.`tipo_embalagem_picole_normal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`ingredientes_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`ingredientes_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`ingredientes_picole_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`ingredientes_picole_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ingredientes` INT NOT NULL,
  `id_picole_ao_leite` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredientes_ao_leite_1_idx` (`id_ingredientes` ASC) VISIBLE,
  INDEX `fk_ingredientes_2_idx` (`id_picole_ao_leite` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_ao_leite_1`
    FOREIGN KEY (`id_ingredientes`)
    REFERENCES `Fabrica_de_sorvete`.`ingredientes_ao_leite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_2`
    FOREIGN KEY (`id_picole_ao_leite`)
    REFERENCES `Fabrica_de_sorvete`.`picole_ao_leite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`tipo_embalagem_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`tipo_embalagem_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`tipos_embalgem_picole_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`tipos_embalgem_picole_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_picole_aoleite` INT NOT NULL,
  `id_embalagem` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_embalagem_33_idx` (`id_picole_aoleite` ASC) VISIBLE,
  INDEX `fk_embalagem_2_idx` (`id_embalagem` ASC) VISIBLE,
  CONSTRAINT `fk_embalagem_1`
    FOREIGN KEY (`id_picole_aoleite`)
    REFERENCES `Fabrica_de_sorvete`.`picole_ao_leite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embalagem_2`
    FOREIGN KEY (`id_embalagem`)
    REFERENCES `Fabrica_de_sorvete`.`tipo_embalagem_ao_leite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`conversantes_ao_leite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`conversantes_ao_leite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`conversantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`conversantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_picole_ao_leite` INT NOT NULL,
  `id_conservantes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conversantes_1_idx` (`id_conservantes` ASC) VISIBLE,
  INDEX `ggg_idx` (`id_picole_ao_leite` ASC) VISIBLE,
  CONSTRAINT `fk_conversantes_1`
    FOREIGN KEY (`id_conservantes`)
    REFERENCES `Fabrica_de_sorvete`.`conversantes_ao_leite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ggg`
    FOREIGN KEY (`id_picole_ao_leite`)
    REFERENCES `Fabrica_de_sorvete`.`picole_ao_leite` (`id_conservantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`lotes_exclusivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`lotes_exclusivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_do_lote` VARCHAR(50) NOT NULL,
  `data_fabricaçao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`lote_picoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`lote_picoles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_picole_normal` INT NOT NULL,
  `id_picole_ao_leite` INT NOT NULL,
  `id_lote` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picole_normal_1_idx` (`id_picole_normal` ASC) VISIBLE,
  INDEX `fk_picole_ao_ao_leite_1_idx` (`id_picole_ao_leite` ASC) VISIBLE,
  INDEX `fk_lote_1_idx` (`id_lote` ASC) VISIBLE,
  CONSTRAINT `fk_picole_normal_1`
    FOREIGN KEY (`id_picole_normal`)
    REFERENCES `Fabrica_de_sorvete`.`picole_normal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picole_ao_ao_leite_1`
    FOREIGN KEY (`id_picole_ao_leite`)
    REFERENCES `Fabrica_de_sorvete`.`picole_ao_leite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_1`
    FOREIGN KEY (`id_lote`)
    REFERENCES `Fabrica_de_sorvete`.`lotes_exclusivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`nota_fiscal` (
  `idl` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idl`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`nota_fiscal_lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`nota_fiscal_lote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_numero_lote` INT NOT NULL,
  `id_quantidade` INT NOT NULL,
  `id_nota_fiscal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_numero_lote_1_idx` (`id_numero_lote` ASC) VISIBLE,
  INDEX `fk_quantidade_1_idx` (`id_quantidade` ASC) VISIBLE,
  INDEX `fk_nota_fiscal_1_idx` (`id_nota_fiscal` ASC) VISIBLE,
  CONSTRAINT `fk_numero_lote_1`
    FOREIGN KEY (`id_numero_lote`)
    REFERENCES `Fabrica_de_sorvete`.`lotes_exclusivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quantidade_1`
    FOREIGN KEY (`id_quantidade`)
    REFERENCES `Fabrica_de_sorvete`.`lotes_exclusivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_fiscal_1`
    FOREIGN KEY (`id_nota_fiscal`)
    REFERENCES `Fabrica_de_sorvete`.`nota_fiscal` (`idl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`revendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`revendedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fabrica_de_sorvete`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fabrica_de_sorvete`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_revendedor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idx` (`id_revendedor` ASC) VISIBLE,
  CONSTRAINT `fk`
    FOREIGN KEY (`id_revendedor`)
    REFERENCES `Fabrica_de_sorvete`.`revendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
